// Generated by CoffeeScript 1.9.3
(function() {
  var be_set, bes, blankableChild, blankableParent, pos_set;

  pos_set = null;

  be_set = true;

  bes = ['be', 'am', 'are', 'is', 'was', 'ware', 'being', 'been'];

  chrome.storage.sync.get({
    pos_set: null,
    be_set: true
  }, function(items) {
    pos_set = items.pos_set;
    return be_set = items.be_set;
  });

  blankableChild = function(visible, invisible, $sp, xml) {
    var $ls, b;
    $ls = $(xml).find("wt").map(function() {
      var pos, word;
      pos = $(this).find("pos").text();
      word = $(this).find("word").text();
      word = pos.match(/^\-LRB\-$/) ? "(" : pos.match(/^\-LRB\-$/) ? ")" : word;
      return $("<span>").attr("class", "blanker-" + pos).text(word);
    });
    $sp.empty();
    $ls.each(function() {
      return $sp.append($(this), ' ');
    });
    pos_set.forEach(function(pos) {
      return $sp.find(".blanker-" + pos).addClass("blankable");
    });
    $sp.find(".blankable").css({
      "border-bottom": "1px solid " + visible
    }).click(function() {
      if ($(this).css("color") === visible) {
        return $(this).css({
          "color": invisible
        });
      } else {
        return $(this).css({
          "color": visible
        });
      }
    });
    b = false;
    $sp.click(function(e) {
      e.stopPropagation();
      if (e.altKey) {
        if (b) {
          $sp.find(".blankable").css({
            "color": invisible
          });
        } else {
          $sp.find(".blankable").css({
            "color": visible
          });
        }
        return b = !b;
      }
    });
    return $sp.find(".blankable").css({
      "color": invisible
    });
  };

  blankableParent = function($dom) {
    var loopy, txts;
    txts = $dom.html().split('<br>').map(function(x) {
      return $("<span>").text($("<p> " + x + " </p>").text());
    });
    $dom.empty();
    txts.forEach(function($sp) {
      return $dom.append($sp).append("<br>");
    });
    loopy = function() {
      var $sp;
      if (txts.length === 0) {
        return;
      }
      $sp = txts.shift();
      return chrome.runtime.sendMessage({
        url: "http://often-test-app.xyz:3000/cont0/chrome_blank",
        type: "0",
        sentence: $sp.text()
      }, function(responseText) {
        var xml;
        xml = $.parseXML(responseText);
        blankableChild($dom.css("color"), $dom.css("background-color"), $sp, xml);
        return loopy();
      });
    };
    return loopy();
  };

  $(function() {
    return $(document).on('click', '*', function(e) {
      if (e.altKey) {
        e.stopPropagation();
        return blankableParent($(this));
      }
    });
  });

}).call(this);
