// Generated by CoffeeScript 1.9.3
(function() {
  var restore_options, save_options, set_default;

  save_options = function() {
    var be, pos;
    pos = $("#POS").val();
    be = $("#be")[0].checked;
    return chrome.storage.sync.set({
      pos_set: pos,
      be_set: be
    }, function() {
      return $("#state").append('saved!');
    });
  };

  restore_options = function() {
    return chrome.storage.sync.get({
      pos_set: null,
      be_set: true
    }, function(items) {
      $("#POS").val(items.pos_set);
      return $("#be").prop('checked', items.be_set);
    });
  };

  set_default = function() {
    $('#POS').val(['JJ', 'JJR', 'JJS', 'VB', 'VBD', 'VBG', 'VBN', 'VBP', 'VBZ']);
    return $('#be').prop('checked', true);
  };

  $(function() {
    restore_options();
    $("#save").click(save_options);
    return $("#default").click(set_default);
  });

}).call(this);
